stages:
  - build
  - push

variables:
  DEV_REGISTRY: "registry.example.com/dev"

build_packages:
  stage: build
  image: crossplane/crossplane-cli:latest
  script:
    - crossplane xpkg build --name config-bundle.xpkg crossplane-bcp/config-bundle
    - crossplane xpkg build --name function-object-reader.xpkg crossplane-bcp/functions/object-reader
    - crossplane xpkg build --name function-git-reader.xpkg crossplane-bcp/functions/git-reader
  artifacts:
    paths:
      - config-bundle.xpkg
      - function-object-reader.xpkg
      - function-git-reader.xpkg

push_packages:
  stage: push
  image: crossplane/crossplane-cli:latest
  script:
    - crossplane xpkg push config-bundle.xpkg ${DEV_REGISTRY}/bcp-config-bundle:latest
    - crossplane xpkg push function-object-reader.xpkg ${DEV_REGISTRY}/function-object-reader:latest
    - crossplane xpkg push function-git-reader.xpkg ${DEV_REGISTRY}/function-git-reader:latest
