stages:
  - build
  - deploy
  - destroy

variables:
  KUBECONFIG: "$CI_PROJECT_DIR/kubeconfig"

build_xpkgs:
  stage: build
  image: crossplane/crossplane-cli:latest
  script:
    - crossplane xpkg build --name provider-configs.xpkg crossplane-bcp/build/providerConfigs
    - crossplane xpkg build --name services.xpkg crossplane-bcp/build/services
    - crossplane xpkg build --name config-bundle.xpkg crossplane-bcp/config-bundle
    - crossplane xpkg build --name jcp-config-bundle.xpkg crossplane-bcp/jcp-config-bundle

build_packages:
  stage: build
  image: crossplane/crossplane-cli:latest
  script:
    - crossplane xpkg build --name config-bundle.xpkg crossplane-bcp/config-bundle
    - crossplane xpkg build --name function-object-reader.xpkg crossplane-bcp/functions/object-reader
    - crossplane xpkg build --name function-git-reader.xpkg crossplane-bcp/functions/git-reader
  artifacts:
    paths:
      - provider-configs.xpkg
      - services.xpkg
      - config-bundle.xpkg
      - jcp-config-bundle.xpkg
      - function-object-reader.xpkg
      - function-git-reader.xpkg

build_helm:
  stage: build
  image: alpine/helm:3.8.2
  script:
    - helm package crossplane-bcp/helm/helm-base
    - helm package crossplane-bcp/helm/helm-jcrs-jcp
  artifacts:
    paths:
      - helm-base-0.1.0.tgz
      - helm-jcrs-jcp-0.1.0.tgz

destroy_bcp:
  stage: destroy
  image: crossplane/crossplane-cli:latest
  script:
    - ./crossplane-bcp/scripts/destroy_bcp.sh

destroy_jcp:
  stage: destroy
  image: crossplane/crossplane-cli:latest
  script:
    - ./crossplane-bcp/scripts/destroy_jcp.sh

deploy_bcp:
  stage: deploy
  image: crossplane/crossplane-cli:latest
  script:
    - echo "$KUBECONFIG_DATA" > ${KUBECONFIG}
    - kubectl crossplane install configuration -f provider-configs.xpkg
    - kubectl crossplane install configuration -f services.xpkg
    - kubectl crossplane install configuration -f config-bundle.xpkg

deploy_jcp:
  stage: deploy
  image: crossplane/crossplane-cli:latest
  needs: ["deploy_bcp"]
  script:
    - echo "$KUBECONFIG_DATA" > ${KUBECONFIG}
    - kubectl crossplane install configuration -f jcp-config-bundle.xpkg

apply_clusterclaim:
  stage: deploy
  image: bitnami/kubectl:latest
  needs: ["deploy_jcp"]
  script:
    - echo "$KUBECONFIG_DATA" > ${KUBECONFIG}
    - kubectl apply -f crossplane-bcp/clusters/jcp/clusterclaim.yaml

